export const ALL_BILL_REQUEST = "ALL_BILL_REQUEST";
export const ALL_BILL_SUCCESS = "ALL_BILL_SUCCESS";
export const ALL_BILL_FAIL = "ALL_BILL_FAIL";

export const BILL_DETAILS_REQUEST = "BILL_DETAILS_REQUEST";
export const BILL_DETAILS_SUCCESS = "BILL_DETAILS_SUCCESS";
export const BILL_DETAILS_FAIL = "BILL_DETAILS_FAIL";

export const NEW_BILL_REQUEST = "NEW_BILL_REQUEST";
export const NEW_BILL_SUCCESS = "NEW_BILL_SUCCESS";
export const NEW_BILL_RESET = "NEW_BILL_RESET";
export const NEW_BILL_FAIL = "NEW_BILL_FAIL";

export const UPDATE_BILL_REQUEST = "UPDATE_BILL_REQUEST";
export const UPDATE_BILL_SUCCESS = "UPDATE_BILL_SUCCESS";
export const UPDATE_BILL_RESET = "UPDATE_BILL_RESET";
export const UPDATE_BILL_FAIL = "UPDATE_BILL_FAIL";

export const DELETE_BILL_REQUEST = "DELETE_BILL_REQUEST";
export const DELETE_BILL_SUCCESS = "DELETE_BILL_SUCCESS";
export const DELETE_BILL_RESET = "DELETE_BILL_RESET";
export const DELETE_BILL_FAIL = "DELETE_BILL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";